version: '3.8'

services:
  app:
    build: .
    ports:
      - "${HOST_PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongodb:27017/pumpshie
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: 